### ISSUE TITLE
DockerSimulator image name missing in constructor call

### ISSUE THREAD

**Issue by vkethana** [r2e-project/r2e#8]
- Current behavior: When the DockerSimulator is instantiated in run_self_equiv.py, no value is passed in for image_name. As a result, the docker image name is hardcoded to "r2e_docker_v4"
- Solution: run_self_equiv.py needs an extra input argument for the image name. However this breaks compatibility with run_tasks_in_parallel_iter because the run_fut_with_port function would need two input args instead of one.

**Comment by manishshettym** [comment]
fwiw: `run_tasks_in_parallel_iter` can take functions with multiple arguments. Here's an example:
https://github.com/r2e-project/r2e/blob/6d0950d85941036067ff38a5c23e68217c8a387c/r2e/generators/testgen/generate.py#L94-L98
